# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spacex/api/telemetron/public/integrations/rate_limit_reason.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'spacex/api/telemetron/public/integrations/rate_limit_reason.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAspacex/api/telemetron/public/integrations/rate_limit_reason.proto\x12)SpaceX.API.Telemetron.Public.Integrations*\xa1\x01\n\x0fRateLimitReason\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08NO_LIMIT\x10\x01\x12\x10\n\x0cPOLICY_LIMIT\x10\x02\x12\x15\n\x11USER_CUSTOM_LIMIT\x10\x03\x12\x11\n\rOVERAGE_LIMIT\x10\x05\x12\x1a\n\x16LOW_SPEED_POLICY_LIMIT\x10\x06\"\x04\x08\x04\x10\x04*\x15HIGH_HOURLY_AVG_LIMITB\xf4\x02\n-com.SpaceX.API.Telemetron.Public.IntegrationsB\x14RateLimitReasonProtoP\x01Zagithub.com/Eitol/starlink-client/libs/golang/client/gen/spacex/api/telemetron/public/integrations\xa2\x02\x05SATPI\xaa\x02)SpaceX.API.Telemetron.Public.Integrations\xca\x02*SpaceX\\API\\Telemetron\\Public_\\Integrations\xe2\x02\x36SpaceX\\API\\Telemetron\\Public_\\Integrations\\GPBMetadata\xea\x02-SpaceX::API::Telemetron::Public::Integrationsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex.api.telemetron.public.integrations.rate_limit_reason_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.SpaceX.API.Telemetron.Public.IntegrationsB\024RateLimitReasonProtoP\001Zagithub.com/Eitol/starlink-client/libs/golang/client/gen/spacex/api/telemetron/public/integrations\242\002\005SATPI\252\002)SpaceX.API.Telemetron.Public.Integrations\312\002*SpaceX\\API\\Telemetron\\Public_\\Integrations\342\0026SpaceX\\API\\Telemetron\\Public_\\Integrations\\GPBMetadata\352\002-SpaceX::API::Telemetron::Public::Integrations'
  _globals['_RATELIMITREASON']._serialized_start=113
  _globals['_RATELIMITREASON']._serialized_end=274
# @@protoc_insertion_point(module_scope)
